#!/bin/bash

set -e

help() {
  echo "Usage ./`basename $0` <parameters>"
  echo "Parameters parsed:"
  echo "  --ext : build name ext (mthive-11-ext) "
  echo "  --hive : help"
  echo "  --rebuild : rebuild hive package"
}

ext=""
rebuild=""
while [ $# -gt 0 ]; do
    case "$1" in
        --ext)
            shift 1
            ext=$1
            shift
            ;;
        --help)
            help
            exit 0
            ;;
        --rebuild)
            shift 1
            rebuild="true"
            ;;
        *)
            break
            ;;
    esac
done

SOURCE_DIR=/Users/code6/git/hive
BUILD_DIR=$SOURCE_DIR/build/dist
CONF_DIR=/Users/code6/git/MT/mthdp/configuration/hive_0.11_production/conf/default
ASSEMBLE_DIR=/Users/code6/PlayGround/hadoop/hive

if [ "$ext" = "" ]; then
    TARGET=mthive-11
else
    TARGET=mthive-11-$ext
fi

TARGET_TARNAME=$TARGET.tar.gz
TARGET_DIR=$ASSEMBLE_DIR/$TARGET
rm -rf $TARGET_DIR
mkdir -p $TARGET_DIR

#copy
if [ "$rebuild" != "" ]; then
    echo "rebuild package..."
    cd $SOURCE_DIR && ant clean package
fi
cp -fR $BUILD_DIR/* $TARGET_DIR
cp -fR $CONF_DIR/* $TARGET_DIR

#tar
cd $ASSEMBLE_DIR
tar -cvzf $TARGET_TARNAME $TARGET/
